apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerdemoapp
  labels:
    app: containerdemoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: containerdemoapp
  template:
    metadata:
      labels:
        app: containerdemoapp
    spec:
      containers:
      - name: containerdemoapp
        image: containerdemoapp:v1
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5 