apiVersion: v1
kind: Service
metadata:
  name: containerdemoapp-service
spec:
  selector:
    app: containerdemoapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8081
  type: NodePort 