apiVersion: v1
kind: Service
metadata:
  name: containerdemoapp-service
  namespace: demo-apps
  labels:
    app: containerdemoapp
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8081
    protocol: TCP
  selector:
    app: containerdemoapp 