apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app
  labels:
    app: dev-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - dev
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "dev"
        effect: "NoSchedule"
      containers:
      - name: dev-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "development" 